eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  info:
    env:
      enable: true
  endpoints:
    web:
      exposure:
        include: health, info
