server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    username: sa
  sql:
    init:
      data-locations: classpath:movie.sql
    jpa:
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: create-drop

info:
  app:
    name: movie-service
    description: Movie Service Application prod
    version: 0.1