server:
  port: 8762

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  application:
    name: eureka-service

management:
  info:
    env:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health, info
info:
  app:
    name: eureka-service
    description: Eureka Service Application
    version: 0.1
